### ISSUE TITLE
Upgrade the dataformat-rdf module to RC02

### ISSUE THREAD

**Issue by sebbader** [eclipse-digitaltwin/aas4j#16]
https://github.com/eclipse-digitaltwin/aas4j/commit/89694e953e5dfeaf4b82233f4dffaae590f56068 has a fixed version of the JSON-LD unit tests. However, I have only fixed the mixins and the main test file. I assume the other rdf files under src/test/resources need to be upgraded, too.

**Comment by changqin26** [comment]
the updates are in the Pull Request https://github.com/eclipse-digitaltwin/aas4j/pull/17, please review.

**Comment by changqin26** [comment]
The issue can be closed because of the merge of PR.
